import type { Profile, Service, Booking, Review } from '@/types/database'

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'host-1',
    full_name: 'Carlos Mendez',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Carlos',
    bio: 'Guia local en Ciudad de Mexico con 5 anos de experiencia. Amo mostrar los secretos de mi ciudad.',
    languages: ['Espanol', 'Ingles'],
    city: 'Ciudad de Mexico',
    country: 'Mexico',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.8,
    total_reviews: 47,
    badges: ['super_host', 'verified'],
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'host-2',
    full_name: 'Maria Garcia',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Maria',
    bio: 'Fotografa profesional. Capturo tus mejores momentos en los lugares mas iconicos de Barcelona.',
    languages: ['Espanol', 'Ingles', 'Frances'],
    city: 'Barcelona',
    country: 'Espana',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.9,
    total_reviews: 82,
    badges: ['super_host', 'top_rated', 'verified'],
    created_at: '2023-11-20T08:00:00Z',
  },
  {
    id: 'host-3',
    full_name: 'Takeshi Yamamoto',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Takeshi',
    bio: 'Traductor japones-espanol. Te ayudo a comunicarte en Tokio sin problemas.',
    languages: ['Japones', 'Espanol', 'Ingles'],
    city: 'Tokio',
    country: 'Japon',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.7,
    total_reviews: 31,
    badges: ['verified'],
    created_at: '2024-03-01T12:00:00Z',
  },
  {
    id: 'host-4',
    full_name: 'Ana Lucia Rios',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=AnaLucia',
    bio: 'Conocedora de la vida nocturna bogotana. Reservas VIP en los mejores lugares.',
    languages: ['Espanol', 'Ingles'],
    city: 'Bogota',
    country: 'Colombia',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.6,
    total_reviews: 28,
    badges: ['verified'],
    created_at: '2024-02-10T14:00:00Z',
  },
  {
    id: 'host-5',
    full_name: 'Pierre Dubois',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Pierre',
    bio: 'Sommelier y amante de la gastronomia parisina. Te consigo la mejor mesa con vista.',
    languages: ['Frances', 'Espanol', 'Ingles'],
    city: 'Paris',
    country: 'Francia',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.9,
    total_reviews: 56,
    badges: ['super_host', 'top_rated', 'verified'],
    created_at: '2023-09-05T09:00:00Z',
  },
]

export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-1',
    host_id: 'host-1',
    type: 'micro_tour',
    title: 'Tour secreto por el Centro Historico',
    description: 'Descubre callejones ocultos, murales y la historia que no cuentan los guias convencionales. Incluye parada en puesto de tacos autenticos.',
    price: 12,
    currency: 'USD',
    duration_minutes: 15,
    latitude: 19.4326,
    longitude: -99.1332,
    address: 'Zocalo, Centro Historico, CDMX',
    photos: [
      'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800',
      'https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=800',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_bookings: 124,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'srv-2',
    host_id: 'host-2',
    type: 'photo_session',
    title: 'Fotos en la Sagrada Familia',
    description: 'Sesion de fotos profesional con los mejores angulos de la Sagrada Familia. Recibes 10 fotos editadas en 24h.',
    price: 18,
    currency: 'USD',
    duration_minutes: 20,
    latitude: 41.4036,
    longitude: 2.1744,
    address: 'Sagrada Familia, Barcelona',
    photos: [
      'https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?w=800',
      'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_bookings: 203,
    created_at: '2024-01-25T08:00:00Z',
  },
  {
    id: 'srv-3',
    host_id: 'host-3',
    type: 'language_assistant',
    title: 'Asistente de japones en Shibuya',
    description: 'Te acompano y traduzco en tiempo real mientras exploras Shibuya. Ideal para compras, restaurantes y transporte.',
    price: 1,
    currency: 'USD',
    duration_minutes: 1,
    latitude: 35.6595,
    longitude: 139.7004,
    address: 'Shibuya Crossing, Tokio',
    photos: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_bookings: 67,
    created_at: '2024-03-05T12:00:00Z',
  },
  {
    id: 'srv-4',
    host_id: 'host-4',
    type: 'vip_access',
    title: 'Skip-the-line Museo del Oro',
    description: 'Entrada prioritaria al Museo del Oro de Bogota. Sin filas, sin esperas. Incluye mapa guia digital.',
    price: 5,
    currency: 'USD',
    duration_minutes: 5,
    latitude: 4.6018,
    longitude: -74.0719,
    address: 'Museo del Oro, Bogota',
    photos: [
      'https://images.unsplash.com/photo-1569930784237-ea65a702c975?w=800',
    ],
    is_active: true,
    rating_avg: 4.6,
    total_bookings: 89,
    created_at: '2024-02-15T14:00:00Z',
  },
  {
    id: 'srv-5',
    host_id: 'host-5',
    type: 'table_reservation',
    title: 'Mesa con vista a la Torre Eiffel',
    description: 'Reserva garantizada en restaurante con vista directa a la Torre Eiffel. Menu degustacion opcional.',
    price: 35,
    currency: 'USD',
    duration_minutes: 10,
    latitude: 48.8584,
    longitude: 2.2945,
    address: 'Trocadero, Paris',
    photos: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_bookings: 156,
    created_at: '2023-09-10T09:00:00Z',
  },
  {
    id: 'srv-6',
    host_id: 'host-1',
    type: 'micro_tour',
    title: 'Coyoacan: Frida Kahlo y mas',
    description: 'Recorrido rapido por Coyoacan. Mercado, Casa Azul (exterior) y callejones bohemios.',
    price: 10,
    currency: 'USD',
    duration_minutes: 15,
    latitude: 19.3500,
    longitude: -99.1627,
    address: 'Coyoacan, CDMX',
    photos: [
      'https://images.unsplash.com/photo-1568736333610-eae6e0ab1e90?w=800',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_bookings: 95,
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'srv-7',
    host_id: 'host-2',
    type: 'photo_session',
    title: 'Golden Hour en Park Guell',
    description: 'Sesion de fotos durante la hora dorada en Park Guell. 15 fotos editadas profesionalmente.',
    price: 20,
    currency: 'USD',
    duration_minutes: 20,
    latitude: 41.4145,
    longitude: 2.1527,
    address: 'Park Guell, Barcelona',
    photos: [
      'https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?w=800',
    ],
    is_active: true,
    rating_avg: 5.0,
    total_bookings: 78,
    created_at: '2024-03-15T08:00:00Z',
  },
  {
    id: 'srv-8',
    host_id: 'host-4',
    type: 'vip_access',
    title: 'Acceso VIP Andres Carne de Res',
    description: 'Sin fila en el legendario Andres. Mesa reservada + trago de bienvenida.',
    price: 15,
    currency: 'USD',
    duration_minutes: 5,
    latitude: 4.8660,
    longitude: -74.0352,
    address: 'Chia, Bogota',
    photos: [
      'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    ],
    is_active: true,
    rating_avg: 4.5,
    total_bookings: 42,
    created_at: '2024-04-10T14:00:00Z',
  },
  {
    id: 'srv-9',
    host_id: 'host-5',
    type: 'table_reservation',
    title: 'Brunch con vista al Sena',
    description: 'Mesa garantizada para brunch dominical junto al Sena. Croissants, champagne y vistas.',
    price: 25,
    currency: 'USD',
    duration_minutes: 10,
    latitude: 48.8566,
    longitude: 2.3522,
    address: 'Ile Saint-Louis, Paris',
    photos: [
      'https://images.unsplash.com/photo-1550353127-b0da3aeaa0ca?w=800',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_bookings: 91,
    created_at: '2024-02-20T09:00:00Z',
  },
  {
    id: 'srv-10',
    host_id: 'host-3',
    type: 'micro_tour',
    title: 'Akihabara en 15 minutos',
    description: 'Lo esencial de Akihabara: tiendas de anime, arcades secretos y la mejor comida callejera.',
    price: 8,
    currency: 'USD',
    duration_minutes: 15,
    latitude: 35.6984,
    longitude: 139.7731,
    address: 'Akihabara, Tokio',
    photos: [
      'https://images.unsplash.com/photo-1528164344705-47542687000d?w=800',
    ],
    is_active: true,
    rating_avg: 4.6,
    total_bookings: 53,
    created_at: '2024-05-01T12:00:00Z',
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    booking_id: 'bk-1',
    reviewer_id: 'user-1',
    reviewee_id: 'host-1',
    rating: 5,
    comment: 'Increible experiencia! Carlos conoce cada rincon del Centro Historico. Los tacos fueron lo mejor.',
    photos: [],
    created_at: '2024-06-01T10:00:00Z',
    reviewer: {
      id: 'user-1',
      full_name: 'Laura Martinez',
      avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Laura',
      bio: null,
      languages: ['Espanol'],
      city: 'Madrid',
      country: 'Espana',
      is_host: false,
      is_explorer: true,
      rating_avg: 0,
      total_reviews: 0,
      badges: [],
      created_at: '2024-05-01T10:00:00Z',
    },
  },
  {
    id: 'rev-2',
    booking_id: 'bk-2',
    reviewer_id: 'user-2',
    reviewee_id: 'host-2',
    rating: 5,
    comment: 'Las fotos quedaron espectaculares. Maria tiene un ojo artistico impresionante.',
    photos: [],
    created_at: '2024-06-05T08:00:00Z',
    reviewer: {
      id: 'user-2',
      full_name: 'Roberto Silva',
      avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Roberto',
      bio: null,
      languages: ['Portugues', 'Espanol'],
      city: 'Sao Paulo',
      country: 'Brasil',
      is_host: false,
      is_explorer: true,
      rating_avg: 0,
      total_reviews: 0,
      badges: [],
      created_at: '2024-05-15T10:00:00Z',
    },
  },
  {
    id: 'rev-3',
    booking_id: 'bk-3',
    reviewer_id: 'user-3',
    reviewee_id: 'host-5',
    rating: 5,
    comment: 'La mesa tenia una vista perfecta de la Torre Eiffel. Pierre es un genio de las reservas.',
    photos: [],
    created_at: '2024-06-10T09:00:00Z',
    reviewer: {
      id: 'user-3',
      full_name: 'Sofia Chen',
      avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia',
      bio: null,
      languages: ['Chino', 'Ingles', 'Espanol'],
      city: 'Shanghai',
      country: 'China',
      is_host: false,
      is_explorer: true,
      rating_avg: 0,
      total_reviews: 0,
      badges: [],
      created_at: '2024-05-20T10:00:00Z',
    },
  },
]

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-demo-1',
    service_id: 'srv-1',
    explorer_id: 'current-user',
    host_id: 'host-1',
    status: 'confirmed',
    scheduled_at: new Date(Date.now() + 86400000 * 2).toISOString(),
    total_price: 12,
    commission_rate: 0.20,
    commission_amount: 2.40,
    stripe_payment_intent_id: 'pi_test_123',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bk-demo-2',
    service_id: 'srv-5',
    explorer_id: 'current-user',
    host_id: 'host-5',
    status: 'completed',
    scheduled_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    total_price: 35,
    commission_rate: 0.20,
    commission_amount: 7.00,
    stripe_payment_intent_id: 'pi_test_456',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
]

// Helper to get host profile for a service
export function getHostForService(serviceId: string): Profile | undefined {
  const service = MOCK_SERVICES.find(s => s.id === serviceId)
  if (!service) return undefined
  return MOCK_PROFILES.find(p => p.id === service.host_id)
}

export function getServiceWithHost(serviceId: string): Service | undefined {
  const service = MOCK_SERVICES.find(s => s.id === serviceId)
  if (!service) return undefined
  return { ...service, host: MOCK_PROFILES.find(p => p.id === service.host_id) }
}
