import type { Profile, Service, Booking, Review } from '@/types/database'

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'host-1',
    full_name: 'Carlos Mendez',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Carlos',
    bio: 'Guia local en Ciudad de Mexico con 5 anos de experiencia. Amo mostrar los secretos de mi ciudad.',
    languages: ['Espanol', 'Ingles'],
    city: 'Ciudad de Mexico',
    country: 'Mexico',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.8,
    total_reviews: 47,
    badges: ['super_host', 'verified'],
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'host-2',
    full_name: 'Maria Garcia',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Maria',
    bio: 'Fotografa profesional. Capturo tus mejores momentos en los lugares mas iconicos de Barcelona.',
    languages: ['Espanol', 'Ingles', 'Frances'],
    city: 'Barcelona',
    country: 'Espana',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.9,
    total_reviews: 82,
    badges: ['super_host', 'top_rated', 'verified'],
    created_at: '2023-11-20T08:00:00Z',
  },
  {
    id: 'host-3',
    full_name: 'Takeshi Yamamoto',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Takeshi',
    bio: 'Traductor japones-espanol. Te ayudo a comunicarte en Tokio sin problemas.',
    languages: ['Japones', 'Espanol', 'Ingles'],
    city: 'Tokio',
    country: 'Japon',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.7,
    total_reviews: 31,
    badges: ['verified'],
    created_at: '2024-03-01T12:00:00Z',
  },
  {
    id: 'host-4',
    full_name: 'Ana Lucia Rios',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=AnaLucia',
    bio: 'Conocedora de la vida nocturna bogotana. Reservas VIP en los mejores lugares.',
    languages: ['Espanol', 'Ingles'],
    city: 'Bogota',
    country: 'Colombia',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.6,
    total_reviews: 28,
    badges: ['verified'],
    created_at: '2024-02-10T14:00:00Z',
  },
  {
    id: 'host-5',
    full_name: 'Pierre Dubois',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Pierre',
    bio: 'Sommelier y amante de la gastronomia parisina. Te consigo la mejor mesa con vista.',
    languages: ['Frances', 'Espanol', 'Ingles'],
    city: 'Paris',
    country: 'Francia',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.9,
    total_reviews: 56,
    badges: ['super_host', 'top_rated', 'verified'],
    created_at: '2023-09-05T09:00:00Z',
  },
  // --- San Rafael, Mendoza hosts (match MOCK_MAP_HOSTS ids) ---
  {
    id: 'host-map-1',
    full_name: 'Lucia Fernandez',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Lucia',
    bio: 'Naci en San Rafael y conozco cada rincon del Canon del Atuel. Sommelier certificada, combino aventura al aire libre con las mejores catas de la region.',
    languages: ['Espanol', 'Ingles'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.8,
    total_reviews: 34,
    badges: ['super_host', 'verified'],
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'host-map-2',
    full_name: 'Martin Rodriguez',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Martin',
    bio: 'Gaucho de tercera generacion. Mis cabalgatas por las sierras de San Rafael te muestran la Mendoza que solo los locales conocen.',
    languages: ['Espanol'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.5,
    total_reviews: 22,
    badges: ['verified'],
    created_at: '2025-05-20T00:00:00Z',
  },
  {
    id: 'host-map-3',
    full_name: 'Camila Lopez',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Camila',
    bio: 'Chef profesional especializada en cocina mendocina. Organizo asados criollos con vista a los vinedos y tours gastronomicos por las mejores bodegas y restaurantes de San Rafael.',
    languages: ['Espanol', 'Ingles', 'Portugues'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.9,
    total_reviews: 51,
    badges: ['super_host', 'top_rated', 'verified'],
    created_at: '2025-04-10T00:00:00Z',
  },
  {
    id: 'host-map-4',
    full_name: 'Diego Alvarez',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Diego',
    bio: 'Guia bilingue y conductor habilitado. Facilito la comunicacion y el transporte para que disfrutes San Rafael sin preocupaciones.',
    languages: ['Espanol', 'Ingles'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.3,
    total_reviews: 18,
    badges: ['verified'],
    created_at: '2025-07-01T00:00:00Z',
  },
  {
    id: 'host-map-5',
    full_name: 'Valentina Ruiz',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Valentina',
    bio: 'Fotografa profesional de paisajes y retratos. Capturo momentos unicos entre vinedos, montanas y los colores del Canon del Atuel.',
    languages: ['Espanol', 'Ingles', 'Italiano'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.7,
    total_reviews: 39,
    badges: ['top_rated', 'verified'],
    created_at: '2025-03-15T00:00:00Z',
  },
  {
    id: 'host-map-6',
    full_name: 'Santiago Perez',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Santiago',
    bio: 'Instructor certificado de rafting y deportes acuaticos. Llevo 8 anos guiando aventuras en el Rio Atuel. Seguridad y adrenalina garantizadas.',
    languages: ['Espanol', 'Ingles'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: false,
    rating_avg: 4.6,
    total_reviews: 27,
    badges: ['verified'],
    created_at: '2025-06-01T00:00:00Z',
  },
  {
    id: 'host-map-7',
    full_name: 'Isabella Torres',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Isabella',
    bio: 'Cocinera y astronoma amateur. De dia te enseno los secretos de la cocina mendocina, de noche te guio bajo el cielo estrellado mas limpio de Argentina.',
    languages: ['Espanol', 'Frances'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.4,
    total_reviews: 15,
    badges: ['verified'],
    created_at: '2025-08-01T00:00:00Z',
  },
  {
    id: 'host-map-8',
    full_name: 'Mateo Garcia',
    avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Mateo',
    bio: 'Amante del ciclismo y la aventura extrema. Organizo rutas en bici por las bodegas y tirolesas en el Canon del Atuel para los que buscan emociones fuertes.',
    languages: ['Espanol', 'Ingles'],
    city: 'San Rafael',
    country: 'Argentina',
    is_host: true,
    is_explorer: true,
    rating_avg: 4.2,
    total_reviews: 12,
    badges: ['verified'],
    created_at: '2025-07-20T00:00:00Z',
  },
]

export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-1',
    host_id: 'host-1',
    type: 'micro_tour',
    title: 'Tour secreto por el Centro Historico',
    description: 'Descubre callejones ocultos, murales y la historia que no cuentan los guias convencionales. Incluye parada en puesto de tacos autenticos.',
    price: 12,
    currency: 'USD',
    duration_minutes: 15,
    latitude: 19.4326,
    longitude: -99.1332,
    address: 'Zocalo, Centro Historico, CDMX',
    photos: [
      'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800',
      'https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=800',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_bookings: 124,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'srv-2',
    host_id: 'host-2',
    type: 'photo_session',
    title: 'Fotos en la Sagrada Familia',
    description: 'Sesion de fotos profesional con los mejores angulos de la Sagrada Familia. Recibes 10 fotos editadas en 24h.',
    price: 18,
    currency: 'USD',
    duration_minutes: 20,
    latitude: 41.4036,
    longitude: 2.1744,
    address: 'Sagrada Familia, Barcelona',
    photos: [
      'https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?w=800',
      'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_bookings: 203,
    created_at: '2024-01-25T08:00:00Z',
  },
  {
    id: 'srv-3',
    host_id: 'host-3',
    type: 'language_assistant',
    title: 'Asistente de japones en Shibuya',
    description: 'Te acompano y traduzco en tiempo real mientras exploras Shibuya. Ideal para compras, restaurantes y transporte.',
    price: 1,
    currency: 'USD',
    duration_minutes: 1,
    latitude: 35.6595,
    longitude: 139.7004,
    address: 'Shibuya Crossing, Tokio',
    photos: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_bookings: 67,
    created_at: '2024-03-05T12:00:00Z',
  },
  {
    id: 'srv-4',
    host_id: 'host-4',
    type: 'vip_access',
    title: 'Skip-the-line Museo del Oro',
    description: 'Entrada prioritaria al Museo del Oro de Bogota. Sin filas, sin esperas. Incluye mapa guia digital.',
    price: 5,
    currency: 'USD',
    duration_minutes: 5,
    latitude: 4.6018,
    longitude: -74.0719,
    address: 'Museo del Oro, Bogota',
    photos: [
      'https://images.unsplash.com/photo-1569930784237-ea65a702c975?w=800',
    ],
    is_active: true,
    rating_avg: 4.6,
    total_bookings: 89,
    created_at: '2024-02-15T14:00:00Z',
  },
  {
    id: 'srv-5',
    host_id: 'host-5',
    type: 'table_reservation',
    title: 'Mesa con vista a la Torre Eiffel',
    description: 'Reserva garantizada en restaurante con vista directa a la Torre Eiffel. Menu degustacion opcional.',
    price: 35,
    currency: 'USD',
    duration_minutes: 10,
    latitude: 48.8584,
    longitude: 2.2945,
    address: 'Trocadero, Paris',
    photos: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_bookings: 156,
    created_at: '2023-09-10T09:00:00Z',
  },
  {
    id: 'srv-6',
    host_id: 'host-1',
    type: 'micro_tour',
    title: 'Coyoacan: Frida Kahlo y mas',
    description: 'Recorrido rapido por Coyoacan. Mercado, Casa Azul (exterior) y callejones bohemios.',
    price: 10,
    currency: 'USD',
    duration_minutes: 15,
    latitude: 19.3500,
    longitude: -99.1627,
    address: 'Coyoacan, CDMX',
    photos: [
      'https://images.unsplash.com/photo-1568736333610-eae6e0ab1e90?w=800',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_bookings: 95,
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'srv-7',
    host_id: 'host-2',
    type: 'photo_session',
    title: 'Golden Hour en Park Guell',
    description: 'Sesion de fotos durante la hora dorada en Park Guell. 15 fotos editadas profesionalmente.',
    price: 20,
    currency: 'USD',
    duration_minutes: 20,
    latitude: 41.4145,
    longitude: 2.1527,
    address: 'Park Guell, Barcelona',
    photos: [
      'https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?w=800',
    ],
    is_active: true,
    rating_avg: 5.0,
    total_bookings: 78,
    created_at: '2024-03-15T08:00:00Z',
  },
  {
    id: 'srv-8',
    host_id: 'host-4',
    type: 'vip_access',
    title: 'Acceso VIP Andres Carne de Res',
    description: 'Sin fila en el legendario Andres. Mesa reservada + trago de bienvenida.',
    price: 15,
    currency: 'USD',
    duration_minutes: 5,
    latitude: 4.8660,
    longitude: -74.0352,
    address: 'Chia, Bogota',
    photos: [
      'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    ],
    is_active: true,
    rating_avg: 4.5,
    total_bookings: 42,
    created_at: '2024-04-10T14:00:00Z',
  },
  {
    id: 'srv-9',
    host_id: 'host-5',
    type: 'table_reservation',
    title: 'Brunch con vista al Sena',
    description: 'Mesa garantizada para brunch dominical junto al Sena. Croissants, champagne y vistas.',
    price: 25,
    currency: 'USD',
    duration_minutes: 10,
    latitude: 48.8566,
    longitude: 2.3522,
    address: 'Ile Saint-Louis, Paris',
    photos: [
      'https://images.unsplash.com/photo-1550353127-b0da3aeaa0ca?w=800',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_bookings: 91,
    created_at: '2024-02-20T09:00:00Z',
  },
  {
    id: 'srv-10',
    host_id: 'host-3',
    type: 'micro_tour',
    title: 'Akihabara en 15 minutos',
    description: 'Lo esencial de Akihabara: tiendas de anime, arcades secretos y la mejor comida callejera.',
    price: 8,
    currency: 'USD',
    duration_minutes: 15,
    latitude: 35.6984,
    longitude: 139.7731,
    address: 'Akihabara, Tokio',
    photos: [
      'https://images.unsplash.com/photo-1528164344705-47542687000d?w=800',
    ],
    is_active: true,
    rating_avg: 4.6,
    total_bookings: 53,
    created_at: '2024-05-01T12:00:00Z',
  },
  // --- San Rafael, Mendoza services (match MOCK_MAP_HOSTS service ids) ---
  {
    id: 'svc-1',
    host_id: 'host-map-1',
    type: 'micro_tour',
    title: 'Tour Canon del Atuel en kayak',
    description: 'Recorrido guiado en kayak por las aguas turquesas del Canon del Atuel. Navegaras entre formaciones rocosas milenarias mientras tu guia te cuenta la historia geologica del lugar. Incluye equipo completo y fotos del recorrido.',
    price: 25,
    currency: 'USD',
    duration_minutes: 90,
    latitude: -34.6150,
    longitude: -68.3280,
    address: 'Canon del Atuel, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1472745433479-4556f22e32c2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_bookings: 45,
    created_at: '2025-07-01T00:00:00Z',
  },
  {
    id: 'svc-2',
    host_id: 'host-map-1',
    type: 'table_reservation',
    title: 'Degustacion de vinos en bodega',
    description: 'Visita una bodega boutique de San Rafael y degusta 5 varietales premium con maridaje de quesos regionales. Lucia te guia por el proceso de elaboracion del Malbec y Cabernet Sauvignon de altura.',
    price: 30,
    currency: 'USD',
    duration_minutes: 75,
    latitude: -34.6155,
    longitude: -68.3275,
    address: 'Bodega artesanal, Ruta 143, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_bookings: 62,
    created_at: '2025-07-01T00:00:00Z',
  },
  {
    id: 'svc-3',
    host_id: 'host-map-2',
    type: 'micro_tour',
    title: 'Cabalgata por la montana',
    description: 'Monta a caballo por senderos de montana con vistas panoramicas a los Andes y los vinedos de San Rafael. Martin, gaucho de tercera generacion, te ensena las tradiciones ecuestres mientras recorren paisajes que quitan el aliento.',
    price: 35,
    currency: 'USD',
    duration_minutes: 120,
    latitude: -34.6200,
    longitude: -68.3350,
    address: 'Finca Los Alamos, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.5,
    total_bookings: 31,
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'svc-4',
    host_id: 'host-map-3',
    type: 'table_reservation',
    title: 'Asado criollo con vista a los vinedos',
    description: 'Disfruta un autentico asado argentino al aire libre con las mejores carnes a la parrilla, empanadas caseras y vino de la zona. Camila cocina frente a vos mientras contemplas las filas de vinedos al atardecer.',
    price: 20,
    currency: 'USD',
    duration_minutes: 120,
    latitude: -34.6130,
    longitude: -68.3330,
    address: 'Finca Doña Carmen, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.9,
    total_bookings: 78,
    created_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'svc-5',
    host_id: 'host-map-3',
    type: 'micro_tour',
    title: 'Tour gastronomico por San Rafael',
    description: 'Recorre los mejores rincones culinarios de San Rafael: bodegas, fabricas de aceite de oliva, queserias artesanales y heladerias premiadas. Tres horas de sabores autenticos con una chef local como guia.',
    price: 18,
    currency: 'USD',
    duration_minutes: 180,
    latitude: -34.6135,
    longitude: -68.3325,
    address: 'Centro, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.8,
    total_bookings: 56,
    created_at: '2025-05-15T00:00:00Z',
  },
  {
    id: 'svc-6',
    host_id: 'host-map-4',
    type: 'language_assistant',
    title: 'Guia bilingue espanol-ingles',
    description: 'Acompanamiento bilingue para turistas de habla inglesa en San Rafael. Diego te asiste en restaurantes, bodegas, excursiones y cualquier situacion donde necesites traduccion en tiempo real.',
    price: 10,
    currency: 'USD',
    duration_minutes: 60,
    latitude: -34.6190,
    longitude: -68.3260,
    address: 'San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.3,
    total_bookings: 24,
    created_at: '2025-07-10T00:00:00Z',
  },
  {
    id: 'svc-7',
    host_id: 'host-map-4',
    type: 'vip_access',
    title: 'Traslado al Canon del Atuel',
    description: 'Servicio de traslado privado desde el centro de San Rafael hasta el Canon del Atuel con paradas panoramicas en los miradores mas espectaculares. Vehiculo confortable con aire acondicionado y agua fresca incluida.',
    price: 15,
    currency: 'USD',
    duration_minutes: 45,
    latitude: -34.6185,
    longitude: -68.3265,
    address: 'Centro de San Rafael a Canon del Atuel, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.4,
    total_bookings: 38,
    created_at: '2025-07-10T00:00:00Z',
  },
  {
    id: 'svc-8',
    host_id: 'host-map-5',
    type: 'photo_session',
    title: 'Sesion de fotos en vinedos',
    description: 'Sesion fotografica profesional entre las hileras de vides con la cordillera de fondo. Ideal para parejas, familias o viajeros que quieren recuerdos unicos. Recibes 20 fotos editadas en 48 horas.',
    price: 30,
    currency: 'USD',
    duration_minutes: 60,
    latitude: -34.6160,
    longitude: -68.3240,
    address: 'Vinedos Ruta 143, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_bookings: 42,
    created_at: '2025-04-01T00:00:00Z',
  },
  {
    id: 'svc-9',
    host_id: 'host-map-5',
    type: 'micro_tour',
    title: 'Trekking Valle Grande',
    description: 'Caminata guiada por el Valle Grande con vistas al embalse y las formaciones rocosas multicolores. Valentina te lleva por senderos poco conocidos y captura fotos del recorrido para que te lleves de recuerdo.',
    price: 22,
    currency: 'USD',
    duration_minutes: 150,
    latitude: -34.6165,
    longitude: -68.3235,
    address: 'Valle Grande, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.7,
    total_bookings: 33,
    created_at: '2025-04-15T00:00:00Z',
  },
  {
    id: 'svc-10',
    host_id: 'host-map-6',
    type: 'vip_access',
    title: 'Rafting en el Rio Atuel',
    description: 'Aventura de rafting clase II-III en las aguas del Rio Atuel. Santiago, instructor certificado con 8 anos de experiencia, garantiza una experiencia segura y llena de adrenalina. Incluye equipo completo, casco, chaleco y briefing de seguridad.',
    price: 40,
    currency: 'USD',
    duration_minutes: 120,
    latitude: -34.6210,
    longitude: -68.3310,
    address: 'Rio Atuel, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1530866495561-507c83b4b909?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.6,
    total_bookings: 29,
    created_at: '2025-06-20T00:00:00Z',
  },
  {
    id: 'svc-11',
    host_id: 'host-map-7',
    type: 'table_reservation',
    title: 'Clase de cocina mendocina',
    description: 'Aprende a preparar empanadas mendocinas, locro y un postre regional en una clase practica con Isabella. Cocinas con ingredientes frescos del mercado local y despues disfrutas todo lo que preparaste.',
    price: 15,
    currency: 'USD',
    duration_minutes: 120,
    latitude: -34.6145,
    longitude: -68.3370,
    address: 'Casa de Isabella, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.5,
    total_bookings: 19,
    created_at: '2025-08-10T00:00:00Z',
  },
  {
    id: 'svc-12',
    host_id: 'host-map-7',
    type: 'micro_tour',
    title: 'Tour nocturno de estrellas',
    description: 'Observacion astronomica en uno de los cielos mas limpios de Argentina. Isabella te guia con telescopio profesional por constelaciones, planetas y la Via Lactea. Incluye mate caliente y facturas caseras bajo las estrellas.',
    price: 20,
    currency: 'USD',
    duration_minutes: 90,
    latitude: -34.6140,
    longitude: -68.3375,
    address: 'Zona rural, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.4,
    total_bookings: 14,
    created_at: '2025-08-15T00:00:00Z',
  },
  {
    id: 'svc-13',
    host_id: 'host-map-8',
    type: 'micro_tour',
    title: 'Alquiler de bici + ruta de bodegas',
    description: 'Recorre en bicicleta las bodegas mas pintorescas de San Rafael a tu ritmo. Mateo te entrega la bici, el mapa con 5 bodegas recomendadas y tips de cada parada. Incluye candado, casco y kit de reparacion.',
    price: 12,
    currency: 'USD',
    duration_minutes: 240,
    latitude: -34.6175,
    longitude: -68.3220,
    address: 'Centro, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.2,
    total_bookings: 17,
    created_at: '2025-07-25T00:00:00Z',
  },
  {
    id: 'svc-14',
    host_id: 'host-map-8',
    type: 'vip_access',
    title: 'Tirolesa en Canon del Atuel',
    description: 'Cruza el Canon del Atuel volando en tirolesa a 80 metros de altura sobre el rio. Una experiencia de adrenalina pura con vistas impresionantes a las paredes rocosas. Mateo supervisa todo el recorrido con equipamiento profesional homologado.',
    price: 28,
    currency: 'USD',
    duration_minutes: 45,
    latitude: -34.6170,
    longitude: -68.3225,
    address: 'Canon del Atuel, San Rafael, Mendoza',
    photos: [
      'https://images.unsplash.com/photo-1622495894307-93143ab2a086?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&h=600&fit=crop',
    ],
    is_active: true,
    rating_avg: 4.3,
    total_bookings: 11,
    created_at: '2025-07-25T00:00:00Z',
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    booking_id: 'bk-1',
    reviewer_id: 'user-1',
    reviewee_id: 'host-1',
    rating: 5,
    comment: 'Increible experiencia! Carlos conoce cada rincon del Centro Historico. Los tacos fueron lo mejor.',
    photos: [],
    created_at: '2024-06-01T10:00:00Z',
    reviewer: {
      id: 'user-1',
      full_name: 'Laura Martinez',
      avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Laura',
      bio: null,
      languages: ['Espanol'],
      city: 'Madrid',
      country: 'Espana',
      is_host: false,
      is_explorer: true,
      rating_avg: 0,
      total_reviews: 0,
      badges: [],
      created_at: '2024-05-01T10:00:00Z',
    },
  },
  {
    id: 'rev-2',
    booking_id: 'bk-2',
    reviewer_id: 'user-2',
    reviewee_id: 'host-2',
    rating: 5,
    comment: 'Las fotos quedaron espectaculares. Maria tiene un ojo artistico impresionante.',
    photos: [],
    created_at: '2024-06-05T08:00:00Z',
    reviewer: {
      id: 'user-2',
      full_name: 'Roberto Silva',
      avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Roberto',
      bio: null,
      languages: ['Portugues', 'Espanol'],
      city: 'Sao Paulo',
      country: 'Brasil',
      is_host: false,
      is_explorer: true,
      rating_avg: 0,
      total_reviews: 0,
      badges: [],
      created_at: '2024-05-15T10:00:00Z',
    },
  },
  {
    id: 'rev-3',
    booking_id: 'bk-3',
    reviewer_id: 'user-3',
    reviewee_id: 'host-5',
    rating: 5,
    comment: 'La mesa tenia una vista perfecta de la Torre Eiffel. Pierre es un genio de las reservas.',
    photos: [],
    created_at: '2024-06-10T09:00:00Z',
    reviewer: {
      id: 'user-3',
      full_name: 'Sofia Chen',
      avatar_url: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia',
      bio: null,
      languages: ['Chino', 'Ingles', 'Espanol'],
      city: 'Shanghai',
      country: 'China',
      is_host: false,
      is_explorer: true,
      rating_avg: 0,
      total_reviews: 0,
      badges: [],
      created_at: '2024-05-20T10:00:00Z',
    },
  },
]

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-demo-1',
    service_id: 'srv-1',
    explorer_id: 'current-user',
    host_id: 'host-1',
    status: 'confirmed',
    scheduled_at: new Date(Date.now() + 86400000 * 2).toISOString(),
    total_price: 12,
    commission_rate: 0.20,
    commission_amount: 2.40,
    stripe_payment_intent_id: 'pi_test_123',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bk-demo-2',
    service_id: 'srv-5',
    explorer_id: 'current-user',
    host_id: 'host-5',
    status: 'completed',
    scheduled_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    total_price: 35,
    commission_rate: 0.20,
    commission_amount: 7.00,
    stripe_payment_intent_id: 'pi_test_456',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
]

// Helper to get host profile for a service
export function getHostForService(serviceId: string): Profile | undefined {
  const service = MOCK_SERVICES.find(s => s.id === serviceId)
  if (!service) return undefined
  return MOCK_PROFILES.find(p => p.id === service.host_id)
}

export function getServiceWithHost(serviceId: string): Service | undefined {
  const service = MOCK_SERVICES.find(s => s.id === serviceId)
  if (!service) return undefined
  return { ...service, host: MOCK_PROFILES.find(p => p.id === service.host_id) }
}
